### ISSUE TITLE
This gem does not support Windows nodes

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/beaker-task_helper#6]
The helper is hardcoded to not run on Windows nodes.

Linux path
https://github.com/puppetlabs/beaker-task_helper/blob/018b57f41f3f2190e340dad229c126b50c4d610c/lib/beaker/task_helper.rb#L30

No WinRM protocol support
https://github.com/puppetlabs/beaker-task_helper/blob/018b57f41f3f2190e340dad229c126b50c4d610c/lib/beaker/task_helper.rb#L56-L62

**Comment by tphoney** [comment]
Yeah i agree, pr's welcome. 
We will eventually get to it.

**Comment by tphoney** [comment]
@glennsarti its not perfect. and it needs more. But it is working functionally now.
